package com.daille.evolutioncards;
import java.util.ArrayList;
import java.util.List;
public final class CardRepository {
    private CardRepository() {}

    public static List<GameCard> getAllCards() {
        List<GameCard> cards = new ArrayList<>();
        cards.add(new GameCard("A1", "Mandíbula Trituradora", "Mandíbula", "Capaz de aplastar presas duras.", "Rareza 2"));
        cards.add(new GameCard("A2", "Colmillos Serrados", "Mandíbula", "Dientes afilados para desgarrar carne.", "Rareza 2"));
        cards.add(new GameCard("A3", "Pico Cortante", "Mandíbula", "Mandíbula en forma de pico para cortar.", "Rareza 3"));
        cards.add(new GameCard("A4", "Mandíbula Canina", "Mandíbula", "Mandíbula para cortar y perforar", "Rareza 2"));
        cards.add(new GameCard("A5", "Mordida Venenosa", "Mandíbula", "Inyecta toxinas al morder.", "Rareza 2"));
        cards.add(new GameCard("A6", "Mandíbula Proyectable", "Mandíbula", "Se extiende rápidamente para capturar presas.", "Rareza 3"));
        cards.add(new GameCard("A7", "Dientes de Aguja", "Mandíbula", "Dientes finos para capturar presas pequeñas y resbaladizas.", "Rareza 3"));
        cards.add(new GameCard("A8", "Mandíbula Filtradora", "Mandíbula", "Filtra alimento del entorno.", "Rareza 2"));
        cards.add(new GameCard("A9", "Pico Perforador", "Mandíbula", "Perfora superficies para acceder a alimento.", "Rareza 2"));
        cards.add(new GameCard("A10", "Mandíbula Omnívora", "Mandíbula", "Adaptada a una dieta variada.", "Rareza 2"));
        cards.add(new GameCard("A11", "Molares Trituradores", "Mandíbula", "Molares fuertes para procesar vegetales.", "Rareza 1"));
        cards.add(new GameCard("A12", "Boca Succionadora", "Mandíbula", "Aspira presas completas mediante succión.", "Rareza 3"));
        cards.add(new GameCard("A13", "Colmillos Curvos", "Mandíbula", "Retiene presas que forcejean.", "Rareza 2"));
        cards.add(new GameCard("A14", "Mandíbula infecciosa", "Mandíbula", "Al morder las bacterias en su boca aplican efectos desconocidos", "Rareza 3"));
        cards.add(new GameCard("A15", "Mandíbula con colmillos", "Mandíbula", "Posee molares y grandes colmillos a sus lados", "Rareza 2"));
        cards.add(new GameCard("A16", "Pelaje Espeso", "Pelaje", "Aísla del frío.", "Rareza 2"));
        cards.add(new GameCard("A17", "Pelaje Impermeable", "Pelaje", "Repele el agua y reduce pérdida de calor.", "Rareza 4"));
        cards.add(new GameCard("A18", "Plumas Aislantes", "Pelaje", "Retienen aire y conservan calor.", "Rareza 0"));
        cards.add(new GameCard("A19", "Caparazón Óseo", "Pelaje", "Protección rígida contra golpes y mordidas.", "Rareza 3"));
        cards.add(new GameCard("A20", "Exoesqueleto Quitinoso", "Pelaje", "Protección externa segmentada y resistente.", "Rareza 4"));
        cards.add(new GameCard("A21", "Escamas Reforzadas", "Pelaje", "Cobertura escamosa que dificulta el daño.", "Rareza 3"));
        cards.add(new GameCard("A22", "Piel Tóxica", "Pelaje", "Secreta sustancias tóxicas como defensa.", "Rareza 3"));
        cards.add(new GameCard("A23", "Piel Gruesa", "Pelaje", "Capa dérmica resistente a impactos.", "Rareza 4"));
        cards.add(new GameCard("A24", "Patrón de Camuflaje", "Pelaje", "Coloración que se mimetiza con el entorno.", "Rareza 3"));
        cards.add(new GameCard("A25", "Cromatogoros", "Pelaje", "cambia de color para mimetizarse con el entorno", "Rareza 3"));
        cards.add(new GameCard("A26", "Piel Elástica", "Pelaje", "Reduce eficacia de mordidas y agarres.", "Rareza 4"));
        cards.add(new GameCard("A27", "Espinas Dérmicas", "Pelaje", "Estructuras punzantes para disuadir ataques.", "Rareza 1"));
        cards.add(new GameCard("A28", "Escamas Plateadas", "Pelaje", "Brillos que confunden a depredadores o presas.", "Rareza 1"));
        cards.add(new GameCard("A29", "Piel Rugosa", "Pelaje", "Superficie áspera que dificulta el agarre.", "Rareza 2"));
        cards.add(new GameCard("A30", "Cobertura Estacional", "Pelaje", "Cambia de grosor o color según la estación.", "Rareza 3"));
        cards.add(new GameCard("A31", "Patas Saltadoras", "Extremidades", "Gran impulso para saltar y evadir.", "Rareza 3"));
        cards.add(new GameCard("A32", "Garras Retráctiles", "Extremidades", "Garras que se esconden para mantener filo.", "Rareza 2"));
        cards.add(new GameCard("A33", "Aletas Potentes", "Extremidades", "Propulsión acuática eficiente.", "Rareza 2"));
        cards.add(new GameCard("A34", "Patas Excavadoras", "Extremidades", "Excavan refugios o buscan alimento bajo tierra.", "Rareza 3"));
        cards.add(new GameCard("A35", "Membrana Planeadora", "Alas", "Planeo entre árboles o desde altura.", "Rareza 3"));
        cards.add(new GameCard("A36", "Alas Batientes", "Alas", "Vuelo activo y maniobrable.", "Rareza 3"));
        cards.add(new GameCard("A37", "Patas Largas", "Extremidades", "Mayor zancada para desplazamiento rápido.", "Rareza 2"));
        cards.add(new GameCard("A38", "Almohadillas Adhesivas", "Extremidades", "Se adhieren a superficies lisas.", "Rareza 2"));
        cards.add(new GameCard("A39", "Extremidades Prensiles", "Extremidades", "Sujeción firme para trepar o manipular.", "Rareza 2"));
        cards.add(new GameCard("A40", "Tentáculos", "Extremidades", "Manipulación flexible y agarre múltiple.", "Rareza 2"));
        cards.add(new GameCard("A41", "Aleta Dorsal Estabilizadora", "Extremidades", "Mejora estabilidad durante el nado.", "Rareza 4"));
        cards.add(new GameCard("A42", "Patas Anchas", "Extremidades", "patas con amplia superficie para no hundirse en la nieve", "Rareza 2"));
        cards.add(new GameCard("A43", "Garras para Cavado", "Extremidades", "Uñas robustas para remover suelo duro.", "Rareza 2"));
        cards.add(new GameCard("A44", "Patas Robustas", "Extremidades", "Extremidades fuertes para empuje y carga.", "Rareza 3"));
        cards.add(new GameCard("A45", "Extremidades Segmentadas", "Extremidades", "Múltiples segmentos para movimientos finos.", "Rareza 3"));
        cards.add(new GameCard("A46", "Alas Cortas", "Alas", "Despegue rápido y maniobra corta.", "Rareza 2"));
        cards.add(new GameCard("A47", "Patas de Aceleración", "Extremidades", "Alta aceleración en carrera.", "Rareza 5"));
        cards.add(new GameCard("A48", "Almohadilla nupcial", "Extremidades", "Aumenta adherencia durante acto reproductivo garantizando fecundación", "Rareza 2"));
        cards.add(new GameCard("A49", "Regeneración de Extremidad", "Extremidades", "Puede regenerar partes perdidas.", "Rareza 1"));
        cards.add(new GameCard("A50", "Patas Trepadoras", "Extremidades", "Adaptadas a escalar y agarrarse.", "Rareza 4"));
        cards.add(new GameCard("A51", "Cola Prensil", "Cola", "Sujeción y equilibrio al trepar.", "Rareza 1"));
        cards.add(new GameCard("A52", "Cola Látigo", "Cola", "Golpe defensivo rápido.", "Rareza 2"));
        cards.add(new GameCard("A53", "Cola Propulsora", "Cola", "Impulso fuerte en el agua.", "Rareza 3"));
        cards.add(new GameCard("A54", "Cola Camuflada", "Cola", "Se confunde con el entorno para evitar detección.", "Rareza 3"));
        cards.add(new GameCard("A55", "Cola Venenosa", "Cola", "Aguijón o toxina en la cola.", "Rareza 2"));
        cards.add(new GameCard("A56", "Cola Afilada", "Cola", "Estructura punzante para defensa o ataque.", "Rareza 2"));
        cards.add(new GameCard("A57", "Cola Equilibradora", "Cola", "Ayuda a estabilizar giros y carrera.", "Rareza 2"));
        cards.add(new GameCard("A58", "Autotomía Caudal", "Cola", "Puede desprender la cola para escapar.", "Rareza 3"));
        cards.add(new GameCard("A59", "Cola Plumosa", "Cola", "Exhibición visual para cortejo o intimidación.", "Rareza 0"));
        cards.add(new GameCard("A60", "Cola bufanda térmica", "Cola", "usada para regular la temperatura", "Rareza 2"));
        cards.add(new GameCard("A61", "Cola Sensorial", "Cola", "Detecta vibraciones o contacto del entorno.", "Rareza 3"));
        cards.add(new GameCard("A62", "Cola Reserva", "Cola", "Almacena grasa/energía en la cola.", "Rareza 2"));
        cards.add(new GameCard("A63", "Cola Natatoria", "Cola", "Mejora el nado prolongado.", "Rareza 3"));
        cards.add(new GameCard("A64", "Cola Cortante", "Cola", "Golpe rápido con borde rígido.", "Rareza 3"));
        cards.add(new GameCard("A65", "Cola Señuelo", "Cola", "Atrae presas imitando un cebo.", "Rareza 2"));
        cards.add(new GameCard("A66", "Visión Nocturna", "Sentido", "Detecta en baja luz.", "Rareza 3"));
        cards.add(new GameCard("A67", "Ojos Compuestos", "Sentido", "Campo visual amplio y sensibilidad al movimiento.", "Rareza 2"));
        cards.add(new GameCard("A68", "Ecolocación", "Sentido", "Localiza por ecos de sonido.", "Rareza 1"));
        cards.add(new GameCard("A69", "Bigotes Sensoriales", "Sentido", "Detecta vibraciones y contacto fino.", "Rareza 2"));
        cards.add(new GameCard("A70", "Línea Lateral", "Sentido", "Detecta vibraciones y movimiento en el agua.", "Rareza 0"));
        cards.add(new GameCard("A71", "Olfato Agudo", "Sentido", "Rastrea señales químicas a distancia.", "Rareza 0"));
        cards.add(new GameCard("A72", "Visión Térmica", "Sentido", "Detecta calor corporal.", "Rareza 2"));
        cards.add(new GameCard("A73", "Audición Direccional", "Sentido", "Ubica la fuente de sonidos con precisión.", "Rareza -1"));
        cards.add(new GameCard("A74", "Electrorrecepción", "Sentido", "Detecta campos eléctricos.", "Rareza 1"));
        cards.add(new GameCard("A75", "Visión Panorámica", "Sentido", "Amplio ángulo visual para detectar amenazas.", "Rareza 2"));
        cards.add(new GameCard("A76", "Detección de Presión", "Sentido", "Percibe cambios de presión y corrientes.", "Rareza 1"));
        cards.add(new GameCard("A77", "Ojos Independientes", "Sentido", "Cada ojo observa en dirección distinta.", "Rareza 2"));
        cards.add(new GameCard("A78", "Sismorrecepción", "Sentido", "Detecta vibraciones del suelo.", "Rareza 2"));
        cards.add(new GameCard("A79", "Super fuerza", "Sentido", "Detecta feromonas y rastros químicos.", "Rareza 2"));
        cards.add(new GameCard("A80", "Visión Ultravioleta", "Sentido", "Ve patrones UV en flores o plumaje.", "Rareza 1"));
        cards.add(new GameCard("A81", "Audición Subacuática", "Sentido", "Percibe sonidos bajo el agua.", "Rareza 2"));
        cards.add(new GameCard("A82", "Sensores de Corriente", "Sentido", "Percibe flujo de aire y vibraciones sutiles.", "Rareza 3"));
        cards.add(new GameCard("A83", "Apotematismo", "Sentido", "coloración de advertencia que señala toxicidad o mal sabor.", "Rareza 0"));
        cards.add(new GameCard("A84", "Osteodermos dérmicos", "Pelaje", "placas oseas bajo la piel", "Rareza 2"));
        cards.add(new GameCard("A85", "Conglobación", "Misceláneos", "enrollarse formando una esfera para proteger partes blandas.", "Rareza 1"));
        cards.add(new GameCard("A86", "Autohémorragia refleja", "Misceláneos", "expulsar hemolinfa/sangre con compuestos repelentes.", "Rareza 2"));
        cards.add(new GameCard("A87", "Sangre Caliente", "Misceláneos", "Mantiene temperatura interna constante.", "Rareza 2"));
        cards.add(new GameCard("A88", "Hibernación", "Misceláneos", "Reduce actividad por periodos para ahorrar energía.", "Rareza -1"));
        cards.add(new GameCard("A89", "Migración Estacional", "Misceláneos", "Viaja por estaciones para encontrar recursos.", "Rareza 3"));
        cards.add(new GameCard("A90", "Reproducción Rápida", "Misceláneos", "Ciclos reproductivos cortos.", "Rareza 2"));
        cards.add(new GameCard("A91", "Cuidado Parental", "Misceláneos", "Protege crías y mejora su supervivencia.", "Rareza 1"));
        cards.add(new GameCard("A92", "Antenas filiformes", "Misceláneos", "Antenas largas y delgadas que aumentan la detección química (feromonas y alimento) a distancia.", "Rareza 2"));
        cards.add(new GameCard("A93", "Bioluminiscencia", "Misceláneos", "Emite luz para atraer o confundir.", "Rareza 0"));
        cards.add(new GameCard("A94", "Metamorfosis Completa", "Misceláneos", "Ciclo de vida con cambios drásticos entre etapas (larva–pupa–adulto), permitiendo roles distintos según la fase.", "Rareza 1"));
        cards.add(new GameCard("A95", "Defensa Química", "Misceláneos", "Expulsa sustancias defensivas.", "Rareza 3"));
        cards.add(new GameCard("A96", "Regeneración Celular", "Misceláneos", "Recupera tejidos dañados rápidamente.", "Rareza 3"));
        cards.add(new GameCard("A97", "Exhibición Intimidante", "Misceláneos", "Posturas/colores para asustar rivales.", "Rareza 2"));
        cards.add(new GameCard("A98", "Simbiosis", "Misceláneos", "Relación mutualista con otra especie.", "Rareza -2"));
        cards.add(new GameCard("A99", "Resistencia a Toxinas", "Misceláneos", "Tolera venenos o toxinas.", "Rareza 3"));
        cards.add(new GameCard("A100", "Especialización Dietaria", "Misceláneos", "Se alimenta de recursos muy específicos.", "Rareza 1"));
        cards.add(new GameCard("A101", "lengua extensible", "Misceláneos", "lengua pegajosa que se dispara para emboscadas", "Rareza 2"));
        cards.add(new GameCard("A102", "Molares de Pastoreo", "Mandíbula", "Molares anchos para cortar y triturar pastos.", "Rareza 3"));
        cards.add(new GameCard("A103", "Mandíbula Rumiadora", "Mandíbula", "Permite rumiar y aprovechar mejor los nutrientes.", "Rareza 3"));
        cards.add(new GameCard("A104", "Incisivos de Roedor", "Mandíbula", "Incisivos que crecen continuamente para cortar fibras duras.", "Rareza 3"));
        cards.add(new GameCard("A105", "Pico Folívoro", "Mandíbula", "Pico/mandíbula adaptada a hojas fibrosas.", "Rareza 1"));
        cards.add(new GameCard("A106", "Mandíbula de Broteo", "Mandíbula", "Especializada en arrancar brotes y hojas altas.", "Rareza 3"));
        cards.add(new GameCard("A107", "Dentición Hipodonta", "Mandíbula", "Dientes altos para dietas abrasivas.", "Rareza 3"));
        cards.add(new GameCard("A108", "Mandíbula Lofodonta", "Mandíbula", "Movimiento lateral para moler vegetales resistentes.", "Rareza 3"));
        cards.add(new GameCard("A109", "Mandíbula Excavadora", "Mandíbula", "Permite arrancar raíces y tubérculos.", "Rareza 0"));
        cards.add(new GameCard("A110", "Boca de Filtrado Vegetal", "Mandíbula", "Filtra algas y microvegetales en agua somera.", "Rareza 2"));
        cards.add(new GameCard("A111", "Dientes en Peine", "Mandíbula", "Raspa algas adheridas a rocas.", "Rareza 1"));
        cards.add(new GameCard("A112", "Pico Granívoro", "Mandíbula", "Pico fuerte para semillas duras.", "Rareza 1"));
        cards.add(new GameCard("A113", "Mandíbula de Corte de Corteza", "Mandíbula", "Arranca corteza y brotes en épocas duras.", "Rareza 2"));
        cards.add(new GameCard("A114", "Boca Succionadora de Néctar", "Mandíbula", "Aprovecha néctar y polen.", "Rareza 2"));
        cards.add(new GameCard("A115", "Mandíbula de Trituración de Conchas Vegetales", "Mandíbula", "Tritura frutos duros y cáscaras.", "Rareza 3"));
        cards.add(new GameCard("A116", "Dentición Selectiva", "Mandíbula", "Selecciona partes más nutritivas de plantas.", "Rareza 3"));
        cards.add(new GameCard("A117", "Patas Dunares", "Extremidades", "Extremidades largas para moverse sobre arena caliente.", "Rareza 2"));
        cards.add(new GameCard("A118", "Pezuñas Escaladoras", "Extremidades", "Pezuñas con agarre para roca y pendientes.", "Rareza 3"));
        cards.add(new GameCard("A119", "Placas de Corteza", "Misceláneos", "Placas dérmicas que imitan madera y protegen del roce.", "Rareza 2"));
        cards.add(new GameCard("A120", "Pelaje Ártico", "Pelaje", "Capa densa que reduce pérdida de calor.", "Rareza 3"));
        cards.add(new GameCard("A121", "Zancada de Pradera", "Extremidades", "Paso largo y eficiente en terreno abierto.", "Rareza 2"));
        cards.add(new GameCard("A122", "Aletas Litorales", "Extremidades", "Aletas y membranas para moverse en aguas someras.", "Rareza 1"));
        cards.add(new GameCard("A123", "Piel Osmorreguladora", "Misceláneos", "Regula sales y evita deshidratación en aguas mixtas.", "Rareza 1"));
        cards.add(new GameCard("A124", "Escamas Reflectantes (Desierto)", "Pelaje", "Superficie clara que refleja radiación y reduce estrés térmico.", "Rareza 3"));
        cards.add(new GameCard("A125", "Garras de Hielo", "Extremidades", "Garras y almohadillas para tracción en hielo.", "Rareza 2"));
        cards.add(new GameCard("A126", "Microhábitat Favorable", "Sentido", "Identifica refugios y rutas seguras del entorno.", "Rareza 2"));
        cards.add(new GameCard("B1", "Desierto", "Bioma", "Ataque: -1 | Percepción: 1 | Temperatura: 4", ""));
        cards.add(new GameCard("B2", "Montaña", "Bioma", "Armadura: 1 | Velocidad: -2 | Temperatura: 3", ""));
        cards.add(new GameCard("B3", "Sabana", "Bioma", "Ataque: 1 | Armadura: -1 | Velocidad: 2 | Percepción: 1 | Temperatura: 2", ""));
        cards.add(new GameCard("B4", "Manglar", "Bioma", "Armadura: -1 | Salud: 1 | Velocidad: -2 | Percepción: 1 | Fertilidad: 1 | Temperatura: 2", ""));
        cards.add(new GameCard("B5", "Jungla", "Bioma", "Ataque: 1 | Percepción: 1 | Temperatura: 2", ""));
        cards.add(new GameCard("B6", "Arrecife", "Bioma", "Ataque: -1 | Armadura: 1 | Salud: 1 | Velocidad: -1 | Percepción: 1", ""));
        cards.add(new GameCard("B7", "Playa", "Bioma", "Armadura: -1 | Velocidad: 1 | Percepción: -1", ""));
        cards.add(new GameCard("B8", "Bosque", "Bioma", "Ataque: 1 | Percepción: 1", ""));
        cards.add(new GameCard("B9", "Llanura", "Bioma", "Armadura: -1 | Velocidad: 2 | Percepción: -1", ""));
        cards.add(new GameCard("B10", "Pradera", "Bioma", "Ataque: 1 | Velocidad: 2 | Percepción: -1 | Fertilidad: -1", ""));
        cards.add(new GameCard("B11", "Taiga", "Bioma", "Velocidad: -1 | Temperatura: -2", ""));
        cards.add(new GameCard("B12", "Estepa", "Bioma", "Ataque: -1 | Velocidad: 1 | Temperatura: -2", ""));
        cards.add(new GameCard("B13", "Tundra", "Bioma", "Ataque: -1 | Salud: -1 | Percepción: -1 | Temperatura: -2", ""));
        cards.add(new GameCard("B14", "Montaña fría", "Bioma", "Armadura: 1 | Velocidad: -1 | Percepción: -1 | Temperatura: -3", ""));
        cards.add(new GameCard("B15", "Glaciares", "Bioma", "Armadura: 1 | Salud: -1 | Velocidad: -1 | Percepción: -1 | Temperatura: -4", ""));
        return cards;
    }
}
